### ISSUE TITLE
Visibility rules that are in the initial config object are not lowercased

### ISSUE THREAD

**Issue by jgerhold** [bassdman/feature-toggle-api#1]
**Describe the bug**
if you initialise the api with some visibility rules. The keys of these rules are not lowercased.
Only rules that are added via the setData/visibility functions are lowercased.

**To Reproduce**
1. Initialise api with rules that have uppercase letters
2. If you check for features with uppercase letters they are not found.

**Expected behavior**
Keys in the initial config are handled the same way as rules that are added after init.

**Comment by sseaman** [comment]
+1, hitting the same issue.  Would be great to get this merged.

**Comment by bassdman** [comment]
Thank you for your advice. I updated the package and the dependency (vue-feature-toggle). Now it's fixed.
